name: nears
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_webrtc: ^0.9.34
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  web_socket_channel: ^2.4.0
  google_fonts: ^5.1.0
  gap: ^3.0.1
  flutter_svg: ^2.0.7
  calendar_date_picker2: ^0.5.2
  device_info_plus: ^9.0.2
  jwt_decoder: ^2.0.1
  dio: ^5.3.0
  flutter_secure_storage: ^8.0.0
  cool_alert: ^2.0.1
  geolocator: ^9.0.2
  just_audio: ^0.9.34
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

    
    

