name: nears
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_webrtc: ^0.9.34
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  web_socket_channel: ^2.4.0
  gap: ^3.0.1
  flutter_svg: ^2.0.7
  calendar_date_picker2: ^0.5.2
  device_info_plus: ^9.0.2
  jwt_decoder: ^2.0.1
  dio: ^5.3.0
  flutter_secure_storage: ^8.0.0
  cool_alert: ^2.0.1
  geolocator: ^9.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  shake: ^2.2.0
  vibration: ^1.8.3
  audioplayers: ^5.2.0
  flutter_isolate: ^2.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura-Bold.ttf
          weight: 700
        - asset: assets/fonts/JuraBook.ttf
          weight: 400
        - asset: assets/fonts/JuraDemiBold.ttf
          weight: 600
        - asset: assets/fonts/JuraLight.ttf
          weight: 300
        - asset: assets/fonts/JuraMedium.ttf
          weight: 500
        - asset: assets/fonts/Jura-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jura-SemiBold.ttf
          weight: 600
    
    

